include: all_lints.yaml

analyzer:
  errors:
    included_file_warning: ignore
  plugins:
    - custom_lint
  exclude:
    - magic_beasts_lints/**

linter:
  rules:
    # Quote preferences
    prefer_double_quotes: false
    prefer_single_quotes: true

    # Type specification
    always_specify_types: false
    omit_local_variable_types: true

    # Final and const usage
    prefer_final_fields: true
    prefer_final_parameters: false
    avoid_final_parameters: true
    prefer_final_locals: false
    unnecessary_final: true

    # Closure parameters
    avoid_types_on_closure_parameters: true

    # Import preferences
    prefer_relative_imports: false
    always_use_package_imports: true

    # Docs
    public_member_api_docs: false
    diagnostic_describe_all_properties: false

    # Syntax
    prefer_expression_function_bodies: false

    # Abstract classes
    avoid_classes_with_only_static_members: false

dart_code_metrics:
  extends:
    - recommended

custom_lint:
  debug: true
  verbose: true
