name: audit

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  analysis:
    name: audit
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to the runner
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Set up Flutter environment
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
      - run: flutter pub get

      # Print Flutter version
      - name: Flutter Version
        run: flutter --version

      # Format code
      - name: Check Code Format
        run: dart format . --set-exit-if-changed

      # Analyze code
      - name: Run Flutter analyze
        run: flutter analyze
